### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mdelapenya** [ardanlabs/gotour#175]
Hi all 👋 I'd like to see this fantastic tour and course to the Spanish language, and **I'd be interested in contributing the translation as a whole**.

I have a local branch that could serve as seed for this, and I wonder if it would be of interest to start pushing it as a PR, and review it in small chunks, given there is a lot of content.

What would it be the preferred way of doing this?

Thanks in advance!

**Comment by mdelapenya** [comment]
Oh I've just found there is a Spanish branch: https://github.com/ardanlabs/gotour/tree/spanish

Will take a look 👀

**Comment by mdelapenya** [comment]
BTW, I noticed that branch is outdated in terms of static files. I've resolved conflicts locally and updated the static files. Not sure if there are content in the article files that are outdated too.

**Comment by pjcalvo** [comment]
Hi Manuel, I have done most of the translations to Spanish. Unfortunately I recently switched jobs and haven't been able to pickup the work from where I left it. 

I don't expect major changes in the articles files, but my good friend @ardan-bkennedy would now more. 

If I were you I would start with those articles that haven't been translated and we can always revisit later those that are already completed. 

Thanks for the help

**Comment by mdelapenya** [comment]
@pjcalvo thanks for the tips! I'll definitively do as you suggest.  I already had the `welcome.article` translated, so I merged both versions into one. Would that be fine for you?

I can push my branch as a PR against the `spanish` branch, and iterate from there. Wdyt?

**Comment by pjcalvo** [comment]
Yeah let’s do that

___________________
Pablo Calvo
Professional Software Engineer


Op do 4 jan 2024 om 17:21 schreef Manuel de la Peña <
***@***.***>

**Comment by mdelapenya** [comment]
@pjcalvo the PR is ready! Please see #179

**Comment by pjcalvo** [comment]
Hi,

I normally stay off my laptop on weekends. I will check it later today

___________________
Pablo Calvo
Professional Software Engineer


Op ma 8 jan 2024 om 07:44 schreef Manuel de la Peña <
***@***.***>
