### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by andrewmkano** [ardanlabs/gotour#223]
Hey folks, I hope you're all doing well.
I'm interested in providing the translations for the site to Spanish.
Although I'm not very familiar with the tools being used for the site in question (https://tour.ardanlabs.com).

Would you please provide some guidance to get started on this 🙏🏽 ?
Thanks in advance

**Comment by ardan-bkennedy** [comment]
I need your email address to add you to the project

**Comment by andrewmkano** [comment]
Done @ardan-bkennedy , thank you 👍🏽

**Comment by andrewmkano** [comment]
amartinez@wawand.co
