### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by PhilippeZeitoun** [ardanlabs/gotour#237]
Hello,

would you be interested in a french translation of the Go Tour ?

As I'll start going through for a refresher, I could translate as I go along.

Regards.

**Comment by ardan-bkennedy** [comment]
Hi. I have @dipandaaser, @alexism, and @scraly working on translations though I am not sure how much they have completed. Can you provide me your email and I will send an email to everyone.

**Comment by PhilippeZeitoun** [comment]
Hi Bill,

Of course!, you can contact me via ***@***.***

Best Regards

Philippe

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by PhilippeZeitoun** [comment]
Sorry I wrote "Hi Bill" but I saw too late it was William, too much courses with Todd McLeod calling you Bill. Hope you don't mind

So, Hi William!

Regards

Philippe Zeitoun
+33652801025

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by PhilippeZeitoun** [comment]
Confused

Now I'm answering you with the old primary mail on Github I changed it yesterday (with other things) for ***@***.***, usually I use Gitlab where things are more up to date than Github (do you prefer I send you a mail directly from the new one to clarify any doubt?).

Philippe

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by ardan-bkennedy** [comment]
Can you send an email to me please at bill@ardanlans.com

**Comment by PhilippeZeitoun** [comment]
Hi again Bill,

did you receive my mail ? as you misspelled your email (I suppose) you wrote 'ardanlans.com" I changed it to "ardanlabs", I hope you received it.

Regards

Philippe

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by PhilippeZeitoun** [comment]
Sent again, I deactivate my GPG key on the account may be some security issue with your mail server (I checked my server logs and it is in a delivered state).

If it fails again I'll add a webmail account on Github and send it to you.

Keep me inform please.
(I enclosed a screencap with the hour of sent messages if you need to check)

Philippe

Envoyé avec la messagerie sécurisée [Proton Mail.](https://proton.me/)

**Comment by scraly** [comment]
Hi,
I was so busy in the past month but I plan to take a look this end of the month :).

**Comment by PhilippeZeitoun** [comment]
Hi @ardan-bkennedy @scraly

I'm starting my Go Tour this week, so I'll be working on translation on the "go" !

Could you explain the process ?
* Do I have to work on main with PR by following instructions in "internal/tour/tour.go" ?
* Do I have to PR creation of a  "fr" folder by PR first ?
* Or working on french branch (it seems the HEAD is far behind the main) ?

I don't know what you prefer but generally when I translate I prefer stick with some english terms like "heap", "stack" instead of literally translate everything but it's up to you.

Regards
Philippe

**Comment by scraly** [comment]
Hi
FYI I created a PR on my side about the translating in french of the welcome article (not a small one ^^):
https://github.com/ardanlabs/gotour/pull/241

**Comment by PhilippeZeitoun** [comment]
I juste reviewed it ;)

**Comment by PhilippeZeitoun** [comment]
so today I translated **variable.article** but can't create a PR (not permitted).

**Comment by ardan-bkennedy** [comment]
I have not set you up yet. hold on.

**Comment by ardan-bkennedy** [comment]
I need you to accept the invite, and then let's close this issue.
