### ISSUE TITLE
Support for having WIP languages without publishing them

### ISSUE THREAD

**Issue by mdelapenya** [ardanlabs/gotour#240]
@ardan-bkennedy I wonder if it's possible to merge a language branch without making it public, so that the changes in the core are applied to that WIP language when they are introduced. Otherwise, we have to go resolving conflicts and keeping track of the changes manually trying not to forget any of them. You know, manually resolving conflicts could lead to mistakes.

_Originally posted by @mdelapenya in https://github.com/ardanlabs/gotour/issues/239#issuecomment-1951302787_

**Comment by ardan-bkennedy** [comment]
I think you are better off merging main into your branch. I have a set of notes of changes that I have to make when main is merged. I can go through that process at any time.

You should look at your branch as main.

**Comment by mdelapenya** [comment]
Indeed, that's what I usually do, see https://github.com/ardanlabs/gotour/pull/239/commits/23e5a00f476730f5c98f8285087cf2edfe417d24. My main concern is not tracking all the changes at once and miss any

**Comment by ardan-bkennedy** [comment]
Everyone on the team should merge to this branch. Everyone has rights to merge
