### ISSUE TITLE
tour: Misspell in the first variables lesson

### ISSUE THREAD

**Issue by vaihdass** [ardanlabs/gotour#258]
Context: https://tour.ardanlabs.com/tour/rus/variables/1

I think it's necessary to replace "(unit...)" to "(uint...)"

"Когда вы объявляете тип данных без указания точности (**`unit`**, int), размер выделяемой памяти зависит от архитектуры компьютера на котором происходит сборка программы:"

**Comment by ardan-bkennedy** [comment]
I will look for that in the entire website.
