### ISSUE TITLE
tour: Wrong function call

### ISSUE THREAD

**Issue by Spuxy** [ardanlabs/gotour#26]
Context: https://tour.ardanlabs.com/tour/error-handling/1

Hey im just reading your great tour but u forgot to change from `errorf()` to `wrapf()`.
At line **67** and **75**.

**Comment by ardan-bkennedy** [comment]
I need to remove the use of Dave's package from these examples. Not sure how I missed that when I brought this content over.

**Comment by ardan-bkennedy** [comment]
I removed Dave's example. I think that solves your problem.
