### ISSUE TITLE
Error at line 38 in answer1.go

### ISSUE THREAD

**Issue by yukendhiran** [ardanlabs/gotour#265]
Context: https://tour.ardanlabs.com/tour/eng/functions/2
Instead of declaration (:=) assignment (=)happen at line 38 in answer1.go

	// Call the function and just check the error on the return.
	_, err = newUser()
	if err != nil {
		fmt.Println(err)
		return
	}

**Comment by ardan-bkennedy** [comment]
I'm looking at the code for the answer and that is what's there and that is correct unless you want to move the if statement up. Which I would normally do.

```
        if _, err := newUser(); err != nil {
		fmt.Println(err)
		return
	}
```

**Comment by yukendhiran** [comment]
![image](https://github.com/ardanlabs/gotour/assets/82448069/203d69af-530d-4bbc-95ff-a77d2f8bdc62)
I dont know but Im gettinng like that at line 38

**Comment by ardan-bkennedy** [comment]
Give me a playground link with the error please. I don't see the problem and the code on the tour doesn't error.
