### ISSUE TITLE
Link to relevant video parts?

### ISSUE THREAD

**Issue by alexbozhenko** [ardanlabs/gotour#31]
For those who purchased the course, it would be nice to have not just a generic link to "ultimate go bundle", but to the actual video.

E.g. this https://github.com/ardanlabs/gotour/blob/7e51fc0d675e6297c432e66d2c6cb78f4401c799/_content/tour/constants.article#L6
would point to:
https://courses.ardanlabs.com/courses/take/ultimate-go/lessons/7419302-2-4-constants
I guess?

Not sure how much work is it to maintain the links though.
But maybe more people will buy the course if they see a link to a relevant video?
Maybe you can also include a short preview for each relevant video, to make people more excited :)

**Comment by ardan-bkennedy** [comment]
Not everyone has a subscription, so this is not possible. I had thought of cutting different videos but it's a lot of work to find those times to provide to the video editor. That would be the best way to do it.  That being said, it would also hurt the sale of the video. So it's a catch-22.

**Comment by alexbozhenko** [comment]
This page  
https://courses.ardanlabs.com/courses/take/ultimate-go/lessons/7419302-2-4-constants
redirects to
https://courses.ardanlabs.com/users/sign_in
when the user is not logged in.

I thought that on sign-in page, you could add a link to https://www.ardanlabs.com/training/individual-on-demand/ultimate-go-bundle/
so that would allow to include links to specific videos in the tour.
But I understand that it is not critical.
The tour is already great on its own!
