### ISSUE TITLE
Update  extra reading section in "errors"?

### ISSUE THREAD

**Issue by alexbozhenko** [ardanlabs/gotour#32]
Context:https://tour.ardanlabs.com/tour/error-handling/1

Link to https://crawshaw.io/blog/xerrors
probably should be replaced with?
https://go.dev/blog/go1.13-errors,
now that it is part of standard library, not a proposal anymore.

Also, maybe https://go.dev/blog/go1.13-errors supersedes https://go.dev/blog/error-handling-and-go ?

Also, the correct link for [Why Go's Error Handling is Awesome](https://rauljordan.com/2020/07/06/why-go-error-handling-is-awesome.html) is: 
https://rauljordan.com/why-go-error-handling-is-awesome/

**Comment by ardan-bkennedy** [comment]
Can you create a PR and add yourself to the CONTRIBUTORS file?
