### ISSUE TITLE
Go tour is not responsive

### ISSUE THREAD

**Issue by leandrorichardardan** [ardanlabs/gotour#36]
To reproduce:

1. Visit https://tour.ardanlabs.com/tour/list;
2. The icons in the header are misaligned when visiting the tour on the phone;
<img width="547" alt="image" src="https://github.com/ardanlabs/web/assets/76958398/c8151080-5bb9-40a8-83a3-aa43aee0236c">

4. Not showing the title:
<img width="449" alt="image" src="https://github.com/ardanlabs/web/assets/76958398/e0694d0c-e595-4944-896e-ffd84d84e959">

**Comment by ardan-bkennedy** [comment]
I am not seeing this in Chrome.

**Comment by leandrorichardardan** [comment]
This is a mobile issue;

The fix would be to hide these buttons when the user is on the mobile. Similar to what the Go Tour does.
