### ISSUE TITLE
Should we translate code comments?

### ISSUE THREAD

**Issue by ardan-bkennedy** [ardanlabs/gotour#56]
I would like to start a discussion about whether we also change comments in code. My first instinct was to say no. For sure I don't want to touch the actual code.

**Comment by Ja7ad** [comment]
> I would like to start a discussion about whether we also change comments in code. My first instinct was to say no. For sure I don't want to touch the actual code.

All things for languages are isolated.

I think we don't have problems with translating all things such as: articles, html and comments

**Comment by ardan-bkennedy** [comment]
@Ja7ad have you been translating comments?

**Comment by Ja7ad** [comment]
> @Ja7ad have you been translating comments?

Currently no, but I think for explicit translation better we translate comments.

**Comment by ardan-bkennedy** [comment]
@Ja7ad You have RTL issues with your language.

**Comment by Ja7ad** [comment]
> @Ja7ad You have RTL issues with your language.

I fix my issue.

Every language have isolated style, js and etc in path `_content/tour/per/static`

**Comment by ardan-bkennedy** [comment]
@Ja7ad I know you did, but this is why you can't update comments in the code?

**Comment by Ja7ad** [comment]
> @Ja7ad I know you did, but this is why you can't update comments in the code?

I don't have issue for update comment in code, you say just article 😅😅

**Comment by Ja7ad** [comment]
> @Ja7ad I know you did, but this is why you can't update comments in the code?

I don't have issue with update comments in the code, you say just translate articles 😅😅.

**Comment by BFostek** [comment]
I don't see any issue with translating the comments.

**Comment by ardan-bkennedy** [comment]
Then I will leave it up to the group for each language. As long as the code itself is not touched I don't have a problem.

**Comment by Ja7ad** [comment]
> Then I will leave it up to the group for each language. As long as the code itself is not touched I don't have a problem.

To translate the language, there is no need to change the original codes at all.

I don't know why `values.js` title and description doesn't applied.

**Comment by raufhm** [comment]
i think many developers understand basic English, especially technical terms. Keeping code comments in English can serve as a consistent "source of truth" and minimize confusion.

**Comment by Ja7ad** [comment]
> i think many developers understand basic English, especially technical terms. Keeping code comments in English can serve as a consistent "source of truth" and minimize confusion. 

Keywords and words that do not have a good equivalent in the language we are translating.  It is better not to be translated.

**Comment by ardan-bkennedy** [comment]
@raufhm you still have a pending invitation.  @Ja7ad values.js for sure needs to be translated.

We need to decide what is best for the user when it comes to comments in the code. I woiuld prefer things to be consistent.

**Comment by Ja7ad** [comment]
> @raufhm you still have a pending invitation.  @Ja7ad values.js for sure needs to be translated.
> 
> We need to decide what is best for the user when it comes to comments in the code. I woiuld prefer things to be consistent.

I translate title and description in `values.js` but on run not changed in home page.

**Comment by ardan-bkennedy** [comment]
You probably need to rebuild the site when anything that is not an article was changed.

**Comment by walvisk** [comment]
i would say leave the comment first since the context already explained in the article. 

I already see some of the codes. Yes, i can translate the comment, provide more understanding. But in some codes like in `_content/tour/ind/welcome/welcome.html` i prefer to to keep as it is (since there is some quote and tweet). so for the sake of consistency, i think we can leave the comment first

**Comment by RemcoE33** [comment]
I would suggest leaving the comments for now. Focus on the context first. 

I cannot speak for other languages here. But in the Netherlands all meetups are in English as well. There is little to no Dutch content available, this means that every developer knows English. So context is the most important part.

**Comment by ardan-bkennedy** [comment]
Right @RemcoE33 so I think each language team needs to decide what is best for their reader.

**Comment by sergiolpf** [comment]
I have no problem in translating the comments. Of course that keywords in comments should be kept in original.

**Comment by drycog** [comment]
Speaking from a completely personal point of view, I detest comments that are not in English  and I would definitely laugh at a source code file with Greek comments, but that's just me. I think it's also practical *not* to translate comments, however I will do it if that's what's expected.

**Comment by viet-wego** [comment]
I couldn't speak English when I was learning to code.
But I was fine with English comments in the code that I read.
So I think it's a "nice to have" not a must when having native language comments.

**Comment by Fiiii** [comment]
+1 for prioritizing content first. In my opinion, comments are an integral part of the technical implementation, and in such cases, English should stay as the 'native' language.

**Comment by yvz5** [comment]
I think comments have valuable information in them which would be lost if not translated. I vote for yes

**Comment by scraly** [comment]
I think the most important thing is to focus on the go tour, the interface, the content :).

**Comment by Fiiii** [comment]
I exported articles names for tracking progress in PRs, enjoy. [LINK](https://github.com/ardanlabs/gotour/pull/68#issue-1910710231)

**Comment by ardan-bkennedy** [comment]
I think the final decision is each team needs to decide what is best for their language translation.
