### ISSUE TITLE
tour: Functions section little mistake

### ISSUE THREAD

**Issue by rschio** [ardanlabs/gotour#66]
https://github.com/ardanlabs/gotour/blob/df52d8dc6203f20e469548145b5aef51d450f439/_content/tour/eng/functions.article#L59-L61

I think this should be:
"Functions can return one or more values (or none, in which case you can omit the 
 return type)..."

**Comment by ardan-bkennedy** [comment]
Yea, I agree that language is off. Can you give me a PR for this fix against main.

**Comment by rschio** [comment]
Sure!
