### ISSUE TITLE
Please create a template/standar for PR reviewing.

### ISSUE THREAD

**Issue by pjcalvo** [ardanlabs/gotour#71]
I think we should agree on a form of PRs for translations.  If you look at the current PR list it is very hard to see wherever it is a translation PR and for what language, and I have to see one by one to check if I can either review or contribute..

I am thinking of:

```
[Translation] [<Language>] : <What are you translating?>
```

Example:

[Translation] [Spanish]: Binary search article.

![image](https://github.com/ardanlabs/gotour/assets/7219896/c1deed6f-1864-4acb-af82-744a5d5625da)

**Comment by pjcalvo** [comment]
I would be happy to also use the language code instead of the full language name:
- en-US
- es-LA
- pt-BR

and so

**Comment by ardan-bkennedy** [comment]
That is a good point. I'll send an email to everyone to review this issue

**Comment by luciormoraes** [comment]
Agreed

**Comment by DipandaAser** [comment]
I agree about this.

May be the language should match the case used on the language branch name.

```
[Translation] [spanish] : <What are you translating?>
[Translation] [portuguese-brazil] : <What are you translating?>
```

**Comment by sergiolpf** [comment]
sounds good to me as well to use language codes.

**Comment by imjenal** [comment]
Agreed. We can use language code. but we'll need to mention it somewhere (as in the PR Guidelines doc) or there may be some link for reference. I found this: https://developers.google.com/admin-sdk/directory/v1/languages

**Comment by tusharxoxoxo** [comment]
agreed, the google article language codes seems pretty fine and standard enough
![image](https://github.com/ardanlabs/gotour/assets/79051850/c866896a-b2a0-4d72-87b0-5915ab1a4b4a)
